steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - us-west1-docker.pkg.dev/sanenews/newsportal/frontend:latest
      - .
images:
  - us-west1-docker.pkg.dev/sanenews/newsportal/frontend:latest