steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - strapi/Dockerfile
      - -t
      - us-west1-docker.pkg.dev/sanenews/newsportal/cms:latest
      - ./strapi
images:
  - us-west1-docker.pkg.dev/sanenews/newsportal/cms:latest